name: Daily Penguin Prediction

on:
  schedule:
    - cron: '30 7 * * *'  # Run at 7:30 AM every day
  workflow_dispatch:  # Allow manual trigger

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests numpy pandas scikit-learn joblib seaborn
    
    - name: Run prediction
      run: python src/api/predict_penguin.py
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add predictions.json
        git commit -m "Update predictions" || exit 0
        git push